### ISSUE TITLE
String, format: uri, allow empty

### ISSUE THREAD

**Issue by Vadorequest** [ajv-validator/ajv#767]
How would you make a format that allow empty URI but requires a valid URI if not empty?

I found the URI regex, I'm thinking about modifying it somehow and use it in my YAML as a variable, or maybe is there a better option?

https://github.com/epoberezkin/ajv/blob/797dfc8c2b0f51aaa405342916cccb5962dd5f21/lib/compile/formats.js#L9

**Comment by epoberezkin** [comment]
You could use anyOf/oneOf rather than trying to put it all in regex.

**Comment by Vadorequest** [comment]
@epoberezkin My understanding was that anyOf/oneOf were for known values, can I use them in this case? I can allow `''` but I don't know what's the URI that is gonna be used. If you have an example it'd be great! Thanks :)

**Comment by Vadorequest** [comment]
Indeed, it's one way to go:

```yaml
  optionalUri: &optionalUri
    anyOf:
    - type: string
      maxLength: 0
    - type: string
      format: uri
```
